gitops-promotion/gitops-promotion-testing

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20220103044321
=> Promote testgroup/testapp in dev to 20220103044321

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20220103044321
=> Promote testgroup/testapp in qa to 20220103044321

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20220103044321
=> Promote testgroup/testapp in prod to 20220103044321

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20220110153735
=> Promote testgroup/testapp in dev to 20220110153735

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20220110153735
=> Promote testgroup/testapp in qa to 20220110153735

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20220110153735
=> Promote testgroup/testapp in prod to 20220110153735

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20220111140139
=> Promote testgroup/testapp in dev to 20220111140139

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20220111140139
=> Promote testgroup/testapp in qa to 20220111140139

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20220111140139
=> Promote testgroup/testapp in prod to 20220111140139

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20220111142006
=> Promote testgroup/testapp in dev to 20220111142006

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20220111142006
=> Promote testgroup/testapp in qa to 20220111142006

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20220111142006
=> Promote testgroup/testapp in prod to 20220111142006

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20220111142102
=> Promote testgroup/testapp in dev to 20220111142102

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20220111142102
=> Promote testgroup/testapp in qa to 20220111142102

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20220111142102
=> Promote testgroup/testapp in prod to 20220111142102

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20220111142141
=> Promote testgroup/testapp in dev to 20220111142141

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20220111142141
=> Promote testgroup/testapp in prod to 20220111142141

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20220111142827
=> Promote testgroup/testapp in qa to 20220111142827

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20220111143830
=> Promote testgroup/testapp in dev to 20220111143830

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20220111143830
=> Promote testgroup/testapp in qa to 20220111143830

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20220111143830
=> Promote testgroup/testapp in prod to 20220111143830

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20220111164338
=> Promote testgroup/testapp in dev to 20220111164338

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20220111164338
=> Promote testgroup/testapp in qa to 20220111164338

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20220111164338
=> Promote testgroup/testapp in prod to 20220111164338

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20220111165943
=> Promote testgroup/testapp in dev to 20220111165943

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20220111165943
=> Promote testgroup/testapp in qa to 20220111165943

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20220111165943
=> Promote testgroup/testapp in prod to 20220111165943

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20220112095957
=> Promote testgroup/testapp in dev to 20220112095957

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20220112095957
=> Promote testgroup/testapp in qa to 20220112095957

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20220112105933
=> Promote testgroup/testapp in dev to 20220112105933

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20220112105933
=> Promote testgroup/testapp in qa to 20220112105933

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20220113120544
=> Promote testgroup/testapp in dev to 20220113120544

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20220113120544
=> Promote testgroup/testapp in prod to 20220113120544

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20220113121532
=> Promote testgroup/testapp in dev to 20220113121532

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20220113121532
=> Promote testgroup/testapp in qa to 20220113121532

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20220113121532
=> Promote testgroup/testapp in prod to 20220113121532

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20220113121549
=> Promote testgroup/testapp in dev to 20220113121549

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20220113121549
=> Promote testgroup/testapp in qa to 20220113121549

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20220113125227
=> Promote testgroup/testapp in dev to 20220113125227

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20220113125227
=> Promote testgroup/testapp in qa to 20220113125227

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20220113125227
=> Promote testgroup/testapp in prod to 20220113125227

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20220113131942
=> Promote testgroup/testapp in dev to 20220113131942

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20220113131942
=> Promote testgroup/testapp in qa to 20220113131942

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20220113131942
=> Promote testgroup/testapp in prod to 20220113131942

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20220113151855
=> Promote testgroup/testapp in dev to 20220113151855

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20220113151855
=> Promote testgroup/testapp in qa to 20220113151855

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20220113151855
=> Promote testgroup/testapp in prod to 20220113151855

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20220113143933
=> Promote testgroup/testapp in dev to 20220113143933

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20220113143933
=> Promote testgroup/testapp in qa to 20220113143933

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20220113143933
=> Promote testgroup/testapp in prod to 20220113143933

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20220113155925
=> Promote testgroup/testapp in dev to 20220113155925

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20220113155925
=> Promote testgroup/testapp in qa to 20220113155925

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20220113155925
=> Promote testgroup/testapp in prod to 20220113155925

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20220118041413
=> Promote testgroup/testapp in dev to 20220118041413

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20220118041413
=> Promote testgroup/testapp in qa to 20220118041413

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20220118041413
=> Promote testgroup/testapp in prod to 20220118041413

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20220120041448
=> Promote testgroup/testapp in dev to 20220120041448

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20220120041448
=> Promote testgroup/testapp in qa to 20220120041448

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20220120041448
=> Promote testgroup/testapp in prod to 20220120041448

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20220124041452
=> Promote testgroup/testapp in dev to 20220124041452

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20220124041452
=> Promote testgroup/testapp in qa to 20220124041452

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20220124041515
=> Promote testgroup/testapp in dev to 20220124041515

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20220124041452
=> Promote testgroup/testapp in prod to 20220124041452

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20220124041515
=> Promote testgroup/testapp in qa to 20220124041515

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20220124041515
=> Promote testgroup/testapp in prod to 20220124041515

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20220126041339
=> Promote testgroup/testapp in dev to 20220126041339

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20220126041339
=> Promote testgroup/testapp in qa to 20220126041339

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20220126041339
=> Promote testgroup/testapp in prod to 20220126041339

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20220128041652
=> Promote testgroup/testapp in dev to 20220128041652

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20220128041652
=> Promote testgroup/testapp in qa to 20220128041652

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20220128041652
=> Promote testgroup/testapp in prod to 20220128041652

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20220128113615
=> Promote testgroup/testapp in dev to 20220128113615

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20220128113615
=> Promote testgroup/testapp in qa to 20220128113615

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20220128113615
=> Promote testgroup/testapp in prod to 20220128113615

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20220128135919
=> Promote testgroup/testapp in dev to 20220128135919

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20220128135919
=> Promote testgroup/testapp in qa to 20220128135919

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20220128135919
=> Promote testgroup/testapp in prod to 20220128135919

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20220128135957
=> Promote testgroup/testapp in dev to 20220128135957

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20220128135957
=> Promote testgroup/testapp in qa to 20220128135957

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20220128135957
=> Promote testgroup/testapp in prod to 20220128135957

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20220128140052
=> Promote testgroup/testapp in dev to 20220128140052

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20220128140052
=> Promote testgroup/testapp in qa to 20220128140052

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20220128140052
=> Promote testgroup/testapp in prod to 20220128140052

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20220131041440
=> Promote testgroup/testapp in qa to 20220131041440

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20220131041440
=> Promote testgroup/testapp in prod to 20220131041440

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20220201041638
=> Promote testgroup/testapp in dev to 20220201041638

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20220201041638
=> Promote testgroup/testapp in qa to 20220201041638

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20220201041638
=> Promote testgroup/testapp in prod to 20220201041638

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20220201161323
=> Promote testgroup/testapp version 20220201161323 to environment dev

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20220201170129
=> Promote testgroup/testapp version 20220201170129 to environment dev

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20220201170129
=> Promote testgroup/testapp version 20220201170129 to environment prod

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20220201172450
=> Promote testgroup/testapp in dev to 20220201172450

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20220201172450
=> Promote testgroup/testapp in qa to 20220201172450

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20220202083202
=> Promote testgroup/testapp version 20220202083202 to environment dev

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20220202083202
=> Promote testgroup/testapp version 20220202083202 to environment qa

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20220202083202
=> Promote testgroup/testapp version 20220202083202 to environment prod

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20220202130131
=> Promote testgroup/testapp version 20220202130131 to environment dev

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20220202130131
=> Promote testgroup/testapp version 20220202130131 to environment qa

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20220202130131
=> Promote testgroup/testapp version 20220202130131 to environment prod

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20220202152542
=> Promote testgroup/testapp version 20220202152542 to environment dev

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20220202152542
=> Promote testgroup/testapp version 20220202152542 to environment qa

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20220202152542
=> Promote testgroup/testapp version 20220202152542 to environment prod

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20220202152610
=> Promote testgroup/testapp version 20220202152610 to environment dev

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20220202152610
=> Promote testgroup/testapp version 20220202152610 to environment qa

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20220202152610
=> Promote testgroup/testapp version 20220202152610 to environment prod

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20220202154208
=> Promote testgroup/testapp version 20220202154208 to environment dev

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20220202154208
=> Promote testgroup/testapp version 20220202154208 to environment qa

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20220202154208
=> Promote testgroup/testapp version 20220202154208 to environment prod

testgroup/dev/kustomization.yaml, testgroup/dev/testapp-20220202154208/kustomization.yaml, testgroup/dev/testapp-20220202154208/~G_v1_Pod--debug-network-pod.yaml
ENV: dev
APP: testapp-20220202154208
TAG: 20220202154208
=> Review testgroup/testapp-20220202154208 feature 20220202154208 in environment dev

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20220203140643
=> Promote testgroup/testapp version 20220203140643 to environment dev

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20220203140643
=> Promote testgroup/testapp version 20220203140643 to environment qa

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20220203140643
=> Promote testgroup/testapp version 20220203140643 to environment prod

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20220203170552
=> Promote testgroup/testapp version 20220203170552 to environment dev

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20220203170552
=> Promote testgroup/testapp version 20220203170552 to environment prod

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20220203221611
=> Promote testgroup/testapp version 20220203221611 to environment dev

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20220203221611
=> Promote testgroup/testapp version 20220203221611 to environment qa

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20220203221611
=> Promote testgroup/testapp version 20220203221611 to environment prod

testgroup/dev/kustomization.yaml, testgroup/dev/testapp-20220203221611/kustomization.yaml, testgroup/dev/testapp-20220203221611/~G_v1_Pod--debug-network-pod.yaml, testgroup/dev/testapp-20220203221611/~G_v1_Pod--debug-network-pod20220202154208.yaml
ENV: dev
APP: testapp
TAG: 20220203221611
=> Review testgroup/testapp feature 20220203221611 in environment dev

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20220204100422
=> Promote testgroup/testapp version 20220204100422 to environment dev

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20220204100422
=> Promote testgroup/testapp version 20220204100422 to environment qa

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20220204100422
=> Promote testgroup/testapp version 20220204100422 to environment prod

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20220204164806
=> Promote testgroup/testapp version 20220204164806 to environment dev

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20220204164806
=> Promote testgroup/testapp version 20220204164806 to environment qa

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20220204164806
=> Promote testgroup/testapp version 20220204164806 to environment prod

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20220204165452
=> Promote testgroup/testapp version 20220204165452 to environment dev

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20220204165452
=> Promote testgroup/testapp version 20220204165452 to environment qa

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20220204165452
=> Promote testgroup/testapp version 20220204165452 to environment prod

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20220207135452
=> Promote testgroup/testapp version 20220207135452 to environment dev

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20220207135452
=> Promote testgroup/testapp version 20220207135452 to environment qa

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20220207135452
=> Promote testgroup/testapp version 20220207135452 to environment prod

testgroup/dev/kustomization.yaml, testgroup/dev/testapp-20220207135452/kustomization.yaml, testgroup/dev/testapp-20220207135452/~G_v1_Pod--debug-network-pod.yaml, testgroup/dev/testapp-20220207135452/~G_v1_Pod--debug-network-pod20220202154208.yaml, testgroup/dev/testapp-20220207135452/~G_v1_Pod--debug-network-pod2022020215420820220203221611.yaml, testgroup/dev/testapp-20220207135452/~G_v1_Pod--debug-network-pod20220203221611.yaml
ENV: dev
APP: testapp
TAG: 20220207135452
=> Review testgroup/testapp feature 20220207135452 in environment dev

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20220207205226
=> Promote testgroup/testapp version 20220207205226 to environment dev

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20220207205226
=> Promote testgroup/testapp version 20220207205226 to environment qa

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20220207205226
=> Promote testgroup/testapp version 20220207205226 to environment prod

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20220207222728
=> Promote testgroup/testapp version 20220207222728 to environment dev

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20220207222728
=> Promote testgroup/testapp version 20220207222728 to environment qa

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20220207222728
=> Promote testgroup/testapp version 20220207222728 to environment prod

testgroup/dev/kustomization.yaml, testgroup/dev/testapp-/kustomization.yaml, testgroup/dev/testapp-/~G_v1_Pod--debug-network-pod.yaml, testgroup/dev/testapp-/~G_v1_Pod--debug-network-pod20220202154208.yaml, testgroup/dev/testapp-/~G_v1_Pod--debug-network-pod2022020215420820220203221611.yaml, testgroup/dev/testapp-/~G_v1_Pod--debug-network-pod202202021542082022020322161120220207135452.yaml, testgroup/dev/testapp-/~G_v1_Pod--debug-network-pod20220202154208202202032216112022020713545220220207205226.yaml, testgroup/dev/testapp-/~G_v1_Pod--debug-network-pod202202021542082022020322161120220207205226.yaml, testgroup/dev/testapp-/~G_v1_Pod--debug-network-pod2022020215420820220207135452.yaml, testgroup/dev/testapp-/~G_v1_Pod--debug-network-pod202202021542082022020713545220220207205226.yaml, testgroup/dev/testapp-/~G_v1_Pod--debug-network-pod2022020215420820220207205226.yaml, testgroup/dev/testapp-/~G_v1_Pod--debug-network-pod20220203221611.yaml, testgroup/dev/testapp-/~G_v1_Pod--debug-network-pod2022020322161120220207135452.yaml, testgroup/dev/testapp-/~G_v1_Pod--debug-network-pod202202032216112022020713545220220207205226.yaml, testgroup/dev/testapp-/~G_v1_Pod--debug-network-pod2022020322161120220207205226.yaml, testgroup/dev/testapp-/~G_v1_Pod--debug-network-pod20220207135452.yaml, testgroup/dev/testapp-/~G_v1_Pod--debug-network-pod2022020713545220220207205226.yaml, testgroup/dev/testapp-/~G_v1_Pod--debug-network-pod20220207205226.yaml
ENV: dev
APP: testapp
TAG: 20220207222728
=> Review testgroup/testapp feature 20220207222728 in environment dev

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20220208095029
=> Promote testgroup/testapp version 20220208095029 to environment dev

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20220208095029
=> Promote testgroup/testapp version 20220208095029 to environment qa

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20220208095029
=> Promote testgroup/testapp version 20220208095029 to environment prod

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20220208100255
=> Promote testgroup/testapp version 20220208100255 to environment dev

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20220208100255
=> Promote testgroup/testapp version 20220208100255 to environment qa

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20220208100255
=> Promote testgroup/testapp version 20220208100255 to environment prod

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20220209102844
=> Promote testgroup/testapp version 20220209102844 to environment dev

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20220209102844
=> Promote testgroup/testapp version 20220209102844 to environment qa

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20220209102844
=> Promote testgroup/testapp version 20220209102844 to environment prod

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20220209111720
=> Promote testgroup/testapp version 20220209111720 to environment dev

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20220209111720
=> Promote testgroup/testapp version 20220209111720 to environment qa

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20220209111720
=> Promote testgroup/testapp version 20220209111720 to environment prod

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20220209134945
=> Promote testgroup/testapp version 20220209134945 to environment dev

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20220209134945
=> Promote testgroup/testapp version 20220209134945 to environment qa

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20220209134945
=> Promote testgroup/testapp version 20220209134945 to environment prod

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20220209213625
=> Promote testgroup/testapp version 20220209213625 to environment dev

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20220209213625
=> Promote testgroup/testapp version 20220209213625 to environment qa

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20220209213625
=> Promote testgroup/testapp version 20220209213625 to environment prod

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20220211041442
=> Promote testgroup/testapp version 20220211041442 to environment dev

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20220211041442
=> Promote testgroup/testapp version 20220211041442 to environment prod

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20220214041537
=> Promote testgroup/testapp version 20220214041537 to environment dev

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20220214041537
=> Promote testgroup/testapp version 20220214041537 to environment qa

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20220214041537
=> Promote testgroup/testapp version 20220214041537 to environment prod

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20220218041833
=> Promote testgroup/testapp version 20220218041833 to environment dev

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20220218041833
=> Promote testgroup/testapp version 20220218041833 to environment qa

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20220218041833
=> Promote testgroup/testapp version 20220218041833 to environment prod

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20220222083157
=> Promote testgroup/testapp version 20220222083157 to environment dev

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20220222083157
=> Promote testgroup/testapp version 20220222083157 to environment qa

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20220222083157
=> Promote testgroup/testapp version 20220222083157 to environment prod

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20220222084128
=> Promote testgroup/testapp version 20220222084128 to environment dev

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20220222084128
=> Promote testgroup/testapp version 20220222084128 to environment qa

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20220222084128
=> Promote testgroup/testapp version 20220222084128 to environment prod

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20220222084701
=> Promote testgroup/testapp version 20220222084701 to environment dev

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20220222084701
=> Promote testgroup/testapp version 20220222084701 to environment qa

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20220222084701
=> Promote testgroup/testapp version 20220222084701 to environment prod

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20220222092934
=> Promote testgroup/testapp version 20220222092934 to environment dev

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20220222092934
=> Promote testgroup/testapp version 20220222092934 to environment qa

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20220222092934
=> Promote testgroup/testapp version 20220222092934 to environment prod

testgroup/dev/kustomization.yaml, testgroup/dev/testapp-foobar/kustomization.yaml, testgroup/dev/testapp-foobar/~G_v1_Pod--debug-network-pod.yaml
ENV: dev
APP: testapp
TAG: 20220222092934
=> Review testgroup/testapp feature 20220222092934 in environment dev

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20220222094709
=> Promote testgroup/testapp version 20220222094709 to environment dev

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20220222094709
=> Promote testgroup/testapp version 20220222094709 to environment qa

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20220222094709
=> Promote testgroup/testapp version 20220222094709 to environment prod

testgroup/dev/testapp-foobar/~G_v1_Pod--debug-network-pod.yaml
ENV: dev
APP: testapp
TAG: 20220222094709
=> Review testgroup/testapp feature 20220222094709 in environment dev

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20220225041326
=> Promote testgroup/testapp version 20220225041326 to environment dev

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20220225041326
=> Promote testgroup/testapp version 20220225041326 to environment qa

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20220225041326
=> Promote testgroup/testapp version 20220225041326 to environment prod

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20220228041836
=> Promote testgroup/testapp version 20220228041836 to environment dev

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20220228041836
=> Promote testgroup/testapp version 20220228041836 to environment qa

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20220228041836
=> Promote testgroup/testapp version 20220228041836 to environment prod

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20220302041730
=> Promote testgroup/testapp version 20220302041730 to environment dev

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20220302041730
=> Promote testgroup/testapp version 20220302041730 to environment qa

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20220302041730
=> Promote testgroup/testapp version 20220302041730 to environment prod

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20220304041514
=> Promote testgroup/testapp version 20220304041514 to environment dev

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20220304041514
=> Promote testgroup/testapp version 20220304041514 to environment qa

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20220304041514
=> Promote testgroup/testapp version 20220304041514 to environment prod

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20220307041641
=> Promote testgroup/testapp version 20220307041641 to environment dev

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20220307041641
=> Promote testgroup/testapp version 20220307041641 to environment qa

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20220307041641
=> Promote testgroup/testapp version 20220307041641 to environment prod

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20220311103336
=> Promote testgroup/testapp version 20220311103336 to environment dev

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20220311103336
=> Promote testgroup/testapp version 20220311103336 to environment qa

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20220311103336
=> Promote testgroup/testapp version 20220311103336 to environment prod

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20220311104509
=> Promote testgroup/testapp version 20220311104509 to environment dev

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20220311104509
=> Promote testgroup/testapp version 20220311104509 to environment qa

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20220311104509
=> Promote testgroup/testapp version 20220311104509 to environment prod

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20220311105325
=> Promote testgroup/testapp version 20220311105325 to environment dev

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20220311105325
=> Promote testgroup/testapp version 20220311105325 to environment qa

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20220311105325
=> Promote testgroup/testapp version 20220311105325 to environment prod

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20220311132434
=> Promote testgroup/testapp version 20220311132434 to environment dev

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20220311132434
=> Promote testgroup/testapp version 20220311132434 to environment qa

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20220311132434
=> Promote testgroup/testapp version 20220311132434 to environment prod

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20220315154355
=> Promote testgroup/testapp version 20220315154355 to environment dev

testgroup/dev/testapp-foobar/~G_v1_Pod--debug-network-pod.yaml
ENV: dev
APP: testapp
TAG: 20220315154355
=> Review testgroup/testapp feature 20220315154355 in environment dev

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20220315160248
=> Promote testgroup/testapp version 20220315160248 to environment dev

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20220315160248
=> Promote testgroup/testapp version 20220315160248 to environment qa

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20220315160248
=> Promote testgroup/testapp version 20220315160248 to environment prod

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20220315160307
=> Promote testgroup/testapp version 20220315160307 to environment dev

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20220315160307
=> Promote testgroup/testapp version 20220315160307 to environment qa

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20220316041609
=> Promote testgroup/testapp version 20220316041609 to environment dev

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20220316041628
=> Promote testgroup/testapp version 20220316041628 to environment dev

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20220316041609
=> Promote testgroup/testapp version 20220316041609 to environment qa

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20220316041640
=> Promote testgroup/testapp version 20220316041640 to environment dev

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20220316041609
=> Promote testgroup/testapp version 20220316041609 to environment prod

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20220317041516
=> Promote testgroup/testapp version 20220317041516 to environment dev

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20220317041516
=> Promote testgroup/testapp version 20220317041516 to environment qa

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20220317041516
=> Promote testgroup/testapp version 20220317041516 to environment prod

testgroup/dev/testapp-foobar/~G_v1_Pod--debug-network-pod.yaml
ENV: dev
APP: testapp
TAG: 20220317041516
=> Review testgroup/testapp feature 20220317041516 in environment dev

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20220318041508
=> Promote testgroup/testapp version 20220318041508 to environment dev

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20220318041508
=> Promote testgroup/testapp version 20220318041508 to environment qa

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20220318041533
=> Promote testgroup/testapp version 20220318041533 to environment dev

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20220318041508
=> Promote testgroup/testapp version 20220318041508 to environment prod

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20220318041533
=> Promote testgroup/testapp version 20220318041533 to environment qa

testgroup/dev/testapp-foobar/~G_v1_Pod--debug-network-pod.yaml
ENV: dev
APP: testapp
TAG: 20220318041508
=> Review testgroup/testapp feature 20220318041508 in environment dev

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20220318041533
=> Promote testgroup/testapp version 20220318041533 to environment prod

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20220321041923
=> Promote testgroup/testapp version 20220321041923 to environment dev

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20220321041923
=> Promote testgroup/testapp version 20220321041923 to environment qa

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20220321041923
=> Promote testgroup/testapp version 20220321041923 to environment prod

testgroup/dev/testapp-foobar/~G_v1_Pod--debug-network-pod.yaml
ENV: dev
APP: testapp
TAG: 20220321041923
=> Review testgroup/testapp feature 20220321041923 in environment dev

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20220322041340
=> Promote testgroup/testapp version 20220322041340 to environment dev

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20220322041340
=> Promote testgroup/testapp version 20220322041340 to environment qa

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20220322041340
=> Promote testgroup/testapp version 20220322041340 to environment prod

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20220323041519
=> Promote testgroup/testapp version 20220323041519 to environment dev

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20220323041519
=> Promote testgroup/testapp version 20220323041519 to environment qa

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20220323041519
=> Promote testgroup/testapp version 20220323041519 to environment prod

testgroup/dev/testapp-foobar/~G_v1_Pod--debug-network-pod.yaml
ENV: dev
APP: testapp
TAG: 20220323041519
=> Review testgroup/testapp feature 20220323041519 in environment dev

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20220324041456
=> Promote testgroup/testapp version 20220324041456 to environment dev

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20220324041456
=> Promote testgroup/testapp version 20220324041456 to environment qa

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20220324041615
=> Promote testgroup/testapp version 20220324041615 to environment dev

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20220324041615
=> Promote testgroup/testapp version 20220324041615 to environment qa

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20220324041632
=> Promote testgroup/testapp version 20220324041632 to environment dev

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20220324041615
=> Promote testgroup/testapp version 20220324041615 to environment prod

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20220324041632
=> Promote testgroup/testapp version 20220324041632 to environment qa

testgroup/dev/testapp-foobar/~G_v1_Pod--debug-network-pod.yaml
ENV: dev
APP: testapp
TAG: 20220324041615
=> Review testgroup/testapp feature 20220324041615 in environment dev

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20220324041632
=> Promote testgroup/testapp version 20220324041632 to environment prod

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20220325041735
=> Promote testgroup/testapp version 20220325041735 to environment dev

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20220325041735
=> Promote testgroup/testapp version 20220325041735 to environment qa

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20220325041735
=> Promote testgroup/testapp version 20220325041735 to environment prod

testgroup/dev/testapp-foobar/~G_v1_Pod--debug-network-pod.yaml
ENV: dev
APP: testapp
TAG: 20220325041735
=> Review testgroup/testapp feature 20220325041735 in environment dev

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20220329041732
=> Promote testgroup/testapp version 20220329041732 to environment dev

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20220329041732
=> Promote testgroup/testapp version 20220329041732 to environment qa

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20220329041732
=> Promote testgroup/testapp version 20220329041732 to environment prod

testgroup/dev/testapp-foobar/~G_v1_Pod--debug-network-pod.yaml
ENV: dev
APP: testapp
TAG: 20220329041732
=> Review testgroup/testapp feature 20220329041732 in environment dev

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20220331041538
=> Promote testgroup/testapp version 20220331041538 to environment dev

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20220331041538
=> Promote testgroup/testapp version 20220331041538 to environment qa

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20220331041538
=> Promote testgroup/testapp version 20220331041538 to environment prod

testgroup/dev/testapp-foobar/~G_v1_Pod--debug-network-pod.yaml
ENV: dev
APP: testapp
TAG: 20220331041538
=> Review testgroup/testapp feature 20220331041538 in environment dev

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20220331041618
=> Promote testgroup/testapp version 20220331041618 to environment dev

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20220331041618
=> Promote testgroup/testapp version 20220331041618 to environment qa

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20220331041618
=> Promote testgroup/testapp version 20220331041618 to environment prod

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20220405041505
=> Promote testgroup/testapp version 20220405041505 to environment dev

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20220405041505
=> Promote testgroup/testapp version 20220405041505 to environment qa

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20220405041505
=> Promote testgroup/testapp version 20220405041505 to environment prod

testgroup/dev/testapp-foobar/~G_v1_Pod--debug-network-pod.yaml
ENV: dev
APP: testapp
TAG: 20220405041505
=> Review testgroup/testapp feature 20220405041505 in environment dev

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20220411041510
=> Promote testgroup/testapp version 20220411041510 to environment dev

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20220412061255
=> Promote testgroup/testapp version 20220412061255 to environment qa

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20220412061255
=> Promote testgroup/testapp version 20220412061255 to environment prod

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20220414041425
=> Promote testgroup/testapp version 20220414041425 to environment dev

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20220415041601
=> Promote testgroup/testapp version 20220415041601 to environment dev

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20220415041601
=> Promote testgroup/testapp version 20220415041601 to environment qa

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20220415041601
=> Promote testgroup/testapp version 20220415041601 to environment prod

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20220415041637
=> Promote testgroup/testapp version 20220415041637 to environment dev

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20220415041637
=> Promote testgroup/testapp version 20220415041637 to environment qa

testgroup/dev/testapp-foobar/~G_v1_Pod--debug-network-pod.yaml
ENV: dev
APP: testapp
TAG: 20220415041601
=> Review testgroup/testapp feature 20220415041601 in environment dev

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20220415041637
=> Promote testgroup/testapp version 20220415041637 to environment prod

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20220420041710
=> Promote testgroup/testapp version 20220420041710 to environment dev

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20220420041710
=> Promote testgroup/testapp version 20220420041710 to environment qa

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20220420041710
=> Promote testgroup/testapp version 20220420041710 to environment prod

testgroup/dev/testapp-foobar/~G_v1_Pod--debug-network-pod.yaml
ENV: dev
APP: testapp
TAG: 20220420041710
=> Review testgroup/testapp feature 20220420041710 in environment dev

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20220421041858
=> Promote testgroup/testapp version 20220421041858 to environment dev

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20220421041858
=> Promote testgroup/testapp version 20220421041858 to environment qa

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20220421041858
=> Promote testgroup/testapp version 20220421041858 to environment prod

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20220422041415
=> Promote testgroup/testapp version 20220422041415 to environment dev

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20220422041415
=> Promote testgroup/testapp version 20220422041415 to environment qa

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20220422041415
=> Promote testgroup/testapp version 20220422041415 to environment prod

testgroup/dev/testapp-foobar/~G_v1_Pod--debug-network-pod.yaml
ENV: dev
APP: testapp
TAG: 20220422041415
=> Review testgroup/testapp feature 20220422041415 in environment dev

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20220422041502
=> Promote testgroup/testapp version 20220422041502 to environment dev

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20220426041837
=> Promote testgroup/testapp version 20220426041837 to environment dev

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20220426041837
=> Promote testgroup/testapp version 20220426041837 to environment qa

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20220426041837
=> Promote testgroup/testapp version 20220426041837 to environment prod

testgroup/dev/testapp-foobar/~G_v1_Pod--debug-network-pod.yaml
ENV: dev
APP: testapp
TAG: 20220426041837
=> Review testgroup/testapp feature 20220426041837 in environment dev

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20220428041340
=> Promote testgroup/testapp version 20220428041340 to environment dev

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20220428041340
=> Promote testgroup/testapp version 20220428041340 to environment qa

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20220428041340
=> Promote testgroup/testapp version 20220428041340 to environment prod

testgroup/dev/testapp-foobar/~G_v1_Pod--debug-network-pod.yaml
ENV: dev
APP: testapp
TAG: 20220428041340
=> Review testgroup/testapp feature 20220428041340 in environment dev

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20220429044156
=> Promote testgroup/testapp version 20220429044156 to environment dev

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20220429044156
=> Promote testgroup/testapp version 20220429044156 to environment qa

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20220429044156
=> Promote testgroup/testapp version 20220429044156 to environment prod

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20220504041502
=> Promote testgroup/testapp version 20220504041502 to environment dev

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20220504041502
=> Promote testgroup/testapp version 20220504041502 to environment qa

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20220504041502
=> Promote testgroup/testapp version 20220504041502 to environment prod

testgroup/dev/testapp-foobar/~G_v1_Pod--debug-network-pod.yaml
ENV: dev
APP: testapp
TAG: 20220504041502
=> Review testgroup/testapp feature 20220504041502 in environment dev

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20220506041308
=> Promote testgroup/testapp version 20220506041308 to environment dev

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20220506041308
=> Promote testgroup/testapp version 20220506041308 to environment qa

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20220506041348
=> Promote testgroup/testapp version 20220506041348 to environment dev

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20220506041308
=> Promote testgroup/testapp version 20220506041308 to environment prod

testgroup/dev/testapp-foobar/~G_v1_Pod--debug-network-pod.yaml
ENV: dev
APP: testapp
TAG: 20220506041308
=> Review testgroup/testapp feature 20220506041308 in environment dev

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20220506041348
=> Promote testgroup/testapp version 20220506041348 to environment qa

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20220506041429
=> Promote testgroup/testapp version 20220506041429 to environment dev

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20220506041348
=> Promote testgroup/testapp version 20220506041348 to environment prod

testgroup/dev/testapp-foobar/~G_v1_Pod--debug-network-pod.yaml
ENV: dev
APP: testapp
TAG: 20220506041348
=> Review testgroup/testapp feature 20220506041348 in environment dev

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20220509042126
=> Promote testgroup/testapp version 20220509042126 to environment dev

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20220509042126
=> Promote testgroup/testapp version 20220509042126 to environment qa

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20220509042126
=> Promote testgroup/testapp version 20220509042126 to environment prod

testgroup/dev/testapp-foobar/~G_v1_Pod--debug-network-pod.yaml
ENV: dev
APP: testapp
TAG: 20220509042126
=> Review testgroup/testapp feature 20220509042126 in environment dev

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20220511041344
=> Promote testgroup/testapp version 20220511041344 to environment dev

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20220511041344
=> Promote testgroup/testapp version 20220511041344 to environment qa

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20220511041344
=> Promote testgroup/testapp version 20220511041344 to environment prod

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20220512041435
=> Promote testgroup/testapp version 20220512041435 to environment dev

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20220512041435
=> Promote testgroup/testapp version 20220512041435 to environment qa

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20220512041435
=> Promote testgroup/testapp version 20220512041435 to environment prod

testgroup/dev/testapp-foobar/~G_v1_Pod--debug-network-pod.yaml
ENV: dev
APP: testapp
TAG: 20220512041435
=> Review testgroup/testapp feature 20220512041435 in environment dev

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20220524041522
=> Promote testgroup/testapp version 20220524041522 to environment dev

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20220524041522
=> Promote testgroup/testapp version 20220524041522 to environment qa

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20220524041522
=> Promote testgroup/testapp version 20220524041522 to environment prod

testgroup/dev/testapp-foobar/~G_v1_Pod--debug-network-pod.yaml
ENV: dev
APP: testapp
TAG: 20220524041522
=> Review testgroup/testapp feature 20220524041522 in environment dev

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20220527041552
=> Promote testgroup/testapp version 20220527041552 to environment dev

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20220527041552
=> Promote testgroup/testapp version 20220527041552 to environment qa

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20220527041552
=> Promote testgroup/testapp version 20220527041552 to environment prod

testgroup/dev/testapp-foobar/~G_v1_Pod--debug-network-pod.yaml
ENV: dev
APP: testapp
TAG: 20220527041552
=> Review testgroup/testapp feature 20220527041552 in environment dev

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20220530041557
=> Promote testgroup/testapp version 20220530041557 to environment dev

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20220530041557
=> Promote testgroup/testapp version 20220530041557 to environment qa

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20220530041557
=> Promote testgroup/testapp version 20220530041557 to environment prod

testgroup/dev/testapp-foobar/~G_v1_Pod--debug-network-pod.yaml
ENV: dev
APP: testapp
TAG: 20220530041557
=> Review testgroup/testapp feature 20220530041557 in environment dev

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20220602041201
=> Promote testgroup/testapp version 20220602041201 to environment dev

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20220602041201
=> Promote testgroup/testapp version 20220602041201 to environment qa

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20220602041201
=> Promote testgroup/testapp version 20220602041201 to environment prod

testgroup/dev/testapp-foobar/~G_v1_Pod--debug-network-pod.yaml
ENV: dev
APP: testapp
TAG: 20220602041201
=> Review testgroup/testapp feature 20220602041201 in environment dev

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20220607041437
=> Promote testgroup/testapp version 20220607041437 to environment dev

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20220607041437
=> Promote testgroup/testapp version 20220607041437 to environment qa

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20220607041437
=> Promote testgroup/testapp version 20220607041437 to environment prod

testgroup/dev/testapp-foobar/~G_v1_Pod--debug-network-pod.yaml
ENV: dev
APP: testapp
TAG: 20220607041437
=> Review testgroup/testapp feature 20220607041437 in environment dev

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20220608041248
=> Promote testgroup/testapp version 20220608041248 to environment dev

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20220608041248
=> Promote testgroup/testapp version 20220608041248 to environment qa

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20220608041248
=> Promote testgroup/testapp version 20220608041248 to environment prod

testgroup/dev/testapp-foobar/~G_v1_Pod--debug-network-pod.yaml
ENV: dev
APP: testapp
TAG: 20220608041248
=> Review testgroup/testapp feature 20220608041248 in environment dev

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20220609041628
=> Promote testgroup/testapp version 20220609041628 to environment dev

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20220609041628
=> Promote testgroup/testapp version 20220609041628 to environment qa

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20220609041628
=> Promote testgroup/testapp version 20220609041628 to environment prod

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20220615041433
=> Promote testgroup/testapp version 20220615041433 to environment dev

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20220615041433
=> Promote testgroup/testapp version 20220615041433 to environment qa

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20220615041433
=> Promote testgroup/testapp version 20220615041433 to environment prod

testgroup/dev/testapp-foobar/~G_v1_Pod--debug-network-pod.yaml
ENV: dev
APP: testapp
TAG: 20220615041433
=> Review testgroup/testapp feature 20220615041433 in environment dev

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20220620041616
=> Promote testgroup/testapp version 20220620041616 to environment dev

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20220620041616
=> Promote testgroup/testapp version 20220620041616 to environment qa

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20220620041616
=> Promote testgroup/testapp version 20220620041616 to environment prod

testgroup/dev/testapp-foobar/~G_v1_Pod--debug-network-pod.yaml
ENV: dev
APP: testapp
TAG: 20220620041616
=> Review testgroup/testapp feature 20220620041616 in environment dev

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20220621041724
=> Promote testgroup/testapp version 20220621041724 to environment dev

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20220621041724
=> Promote testgroup/testapp version 20220621041724 to environment qa

testgroup/dev/testapp-foobar/~G_v1_Pod--debug-network-pod.yaml
ENV: dev
APP: testapp
TAG: 20220621041724
=> Review testgroup/testapp feature 20220621041724 in environment dev

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20220627041246
=> Promote testgroup/testapp version 20220627041246 to environment dev

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20220627041246
=> Promote testgroup/testapp version 20220627041246 to environment qa

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20220627041246
=> Promote testgroup/testapp version 20220627041246 to environment prod

testgroup/dev/testapp-foobar/~G_v1_Pod--debug-network-pod.yaml
ENV: dev
APP: testapp
TAG: 20220627041246
=> Review testgroup/testapp feature 20220627041246 in environment dev

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20220630041810
=> Promote testgroup/testapp version 20220630041810 to environment dev

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20220630041810
=> Promote testgroup/testapp version 20220630041810 to environment qa

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20220630041810
=> Promote testgroup/testapp version 20220630041810 to environment prod

testgroup/dev/testapp-foobar/~G_v1_Pod--debug-network-pod.yaml
ENV: dev
APP: testapp
TAG: 20220630041810
=> Review testgroup/testapp feature 20220630041810 in environment dev

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20220704041531
=> Promote testgroup/testapp version 20220704041531 to environment dev

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20220704041531
=> Promote testgroup/testapp version 20220704041531 to environment qa

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20220704041531
=> Promote testgroup/testapp version 20220704041531 to environment prod

testgroup/dev/testapp-foobar/~G_v1_Pod--debug-network-pod.yaml
ENV: dev
APP: testapp
TAG: 20220704041531
=> Review testgroup/testapp feature 20220704041531 in environment dev
