testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20210713224310
=> Promote testgroup/testapp in dev to 20210713224310

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20210713224310
=> Promote testgroup/testapp in qa to 20210713224310

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20210901074450
=> Promote testgroup/testapp in dev to 20210901074450

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20210901074450
=> Promote testgroup/testapp in qa to 20210901074450

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20210901074450
=> Promote testgroup/testapp in prod to 20210901074450

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20210901075819
=> Promote testgroup/testapp in dev to 20210901075819

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20210901075819
=> Promote testgroup/testapp in qa to 20210901075819

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20210901075819
=> Promote testgroup/testapp in prod to 20210901075819

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20210901101118
=> Promote testgroup/testapp in dev to 20210901101118

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20210901101118
=> Promote testgroup/testapp in qa to 20210901101118

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20210901101118
=> Promote testgroup/testapp in prod to 20210901101118

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20210901081850
=> Promote testgroup/testapp in dev to 20210901081850

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20210901081850
=> Promote testgroup/testapp in qa to 20210901081850

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20210901081850
=> Promote testgroup/testapp in prod to 20210901081850

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20210901082955
=> Promote testgroup/testapp in dev to 20210901082955

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20210901082955
=> Promote testgroup/testapp in qa to 20210901082955

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20210901082955
=> Promote testgroup/testapp in prod to 20210901082955

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20210901083855
=> Promote testgroup/testapp in dev to 20210901083855

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20210901084626
=> Promote testgroup/testapp in dev to 20210901084626

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20210901084626
=> Promote testgroup/testapp in qa to 20210901084626

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20210901084626
=> Promote testgroup/testapp in prod to 20210901084626

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20210901085143
=> Promote testgroup/testapp in dev to 20210901085143

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20210901085143
=> Promote testgroup/testapp in qa to 20210901085143

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20210901085143
=> Promote testgroup/testapp in prod to 20210901085143

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20210901085842
=> Promote testgroup/testapp in dev to 20210901085842

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20210901085842
=> Promote testgroup/testapp in qa to 20210901085842

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20210901085842
=> Promote testgroup/testapp in prod to 20210901085842

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20210901093637
=> Promote testgroup/testapp in dev to 20210901093637

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20210901093637
=> Promote testgroup/testapp in qa to 20210901093637

testgroup/dev/testapp.yaml
ENV: prod
APP: testapp
TAG: 20210901093637
=> Promote testgroup/testapp in prod to 20210901093637

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20210901164351
=> Promote testgroup/testapp in dev to 20210901164351

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20210901164351
=> Promote testgroup/testapp in qa to 20210901164351

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20210901164351
=> Promote testgroup/testapp in prod to 20210901164351

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20210901144913
=> Promote testgroup/testapp in qa to 20210901144913

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20210901144913
=> Promote testgroup/testapp in prod to 20210901144913

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20210901145402
=> Promote testgroup/testapp in dev to 20210901145402

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20210901145402
=> Promote testgroup/testapp in qa to 20210901145402

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20210901145402
=> Promote testgroup/testapp in prod to 20210901145402

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20210901145957
=> Promote testgroup/testapp in dev to 20210901145957

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20210901145957
=> Promote testgroup/testapp in qa to 20210901145957

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20210901145957
=> Promote testgroup/testapp in prod to 20210901145957

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20210902131619
=> Promote testgroup/testapp in qa to 20210902131619

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20210902131619
=> Promote testgroup/testapp in prod to 20210902131619

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20210902123228
=> Promote testgroup/testapp in dev to 20210902123228

testgroup/dev/testapp.yaml
ENV: qa
APP: testapp
TAG: 20210902123228
=> Promote testgroup/testapp in qa to 20210902123228

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20210902153416
=> Promote testgroup/testapp in dev to 20210902153416

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20210902153416
=> Promote testgroup/testapp in qa to 20210902153416

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20210903064323
=> Promote testgroup/testapp in dev to 20210903064323

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20210903064323
=> Promote testgroup/testapp in qa to 20210903064323

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20210903064323
=> Promote testgroup/testapp in prod to 20210903064323

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20210903072800
=> Promote testgroup/testapp in dev to 20210903072800

testgroup/dev/testapp.yaml
ENV: qa
APP: testapp
TAG: 20210903072800
=> Promote testgroup/testapp in qa to 20210903072800

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20210903084319
=> Promote testgroup/testapp in dev to 20210903084319

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20210903084319
=> Promote testgroup/testapp in qa to 20210903084319

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20210903084923
=> Promote testgroup/testapp in dev to 20210903084923

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20210903084923
=> Promote testgroup/testapp in qa to 20210903084923

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20210903090058
=> Promote testgroup/testapp in dev to 20210903090058

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20210903090058
=> Promote testgroup/testapp in qa to 20210903090058

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20210903090058
=> Promote testgroup/testapp in prod to 20210903090058

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20210903090524
=> Promote testgroup/testapp in dev to 20210903090524

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20210903091108
=> Promote testgroup/testapp in dev to 20210903091108

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20210903111516
=> Promote testgroup/testapp in dev to 20210903111516

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20210903111516
=> Promote testgroup/testapp in qa to 20210903111516

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20210903111516
=> Promote testgroup/testapp in prod to 20210903111516

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20210903092910
=> Promote testgroup/testapp in dev to 20210903092910

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20210903092910
=> Promote testgroup/testapp in qa to 20210903092910

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20210903113506
=> Promote testgroup/testapp in dev to 20210903113506

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20210903113506
=> Promote testgroup/testapp in qa to 20210903113506

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20210903113506
=> Promote testgroup/testapp in prod to 20210903113506

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20210903094221
=> Promote testgroup/testapp in dev to 20210903094221

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20210903094221
=> Promote testgroup/testapp in qa to 20210903094221

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20210903094221
=> Promote testgroup/testapp in prod to 20210903094221

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20210903094841
=> Promote testgroup/testapp in dev to 20210903094841

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20210903094841
=> Promote testgroup/testapp in qa to 20210903094841

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20210903094841
=> Promote testgroup/testapp in prod to 20210903094841

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20210903095322
=> Promote testgroup/testapp in dev to 20210903095322

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20210903095322
=> Promote testgroup/testapp in qa to 20210903095322

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20210903095322
=> Promote testgroup/testapp in prod to 20210903095322

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20210903105322
=> Promote testgroup/testapp in dev to 20210903105322

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20210903105322
=> Promote testgroup/testapp in qa to 20210903105322

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20210903105322
=> Promote testgroup/testapp in prod to 20210903105322

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20210903110805
=> Promote testgroup/testapp in dev to 20210903110805

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20210903110805
=> Promote testgroup/testapp in qa to 20210903110805

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20210903110805
=> Promote testgroup/testapp in prod to 20210903110805

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20210903113145
=> Promote testgroup/testapp in dev to 20210903113145

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20210903113145
=> Promote testgroup/testapp in qa to 20210903113145

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20210903113145
=> Promote testgroup/testapp in prod to 20210903113145

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20210903140011
=> Promote testgroup/testapp in dev to 20210903140011

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20210903140340
=> Promote testgroup/testapp in dev to 20210903140340

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20210903141406
=> Promote testgroup/testapp in dev to 20210903141406

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20210903141917
=> Promote testgroup/testapp in dev to 20210903141917

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20210903142315
=> Promote testgroup/testapp in dev to 20210903142315

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20210903142315
=> Promote testgroup/testapp in qa to 20210903142315

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20210903142315
=> Promote testgroup/testapp in prod to 20210903142315

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20210903143036
=> Promote testgroup/testapp in dev to 20210903143036

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20210903143036
=> Promote testgroup/testapp in qa to 20210903143036

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20210903143036
=> Promote testgroup/testapp in prod to 20210903143036

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20210903123723
=> Promote testgroup/testapp in dev to 20210903123723

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20210903124528
=> Promote testgroup/testapp in dev to 20210903124528

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20210903124528
=> Promote testgroup/testapp in qa to 20210903124528

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20210903124528
=> Promote testgroup/testapp in prod to 20210903124528

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20210903124937
=> Promote testgroup/testapp in dev to 20210903124937

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20210903124937
=> Promote testgroup/testapp in qa to 20210903124937

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20210903124937
=> Promote testgroup/testapp in prod to 20210903124937

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20210903150619
=> Promote testgroup/testapp in dev to 20210903150619

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20210903150619
=> Promote testgroup/testapp in qa to 20210903150619

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20210903150619
=> Promote testgroup/testapp in prod to 20210903150619

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20210903130950
=> Promote testgroup/testapp in dev to 20210903130950

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20210903130950
=> Promote testgroup/testapp in qa to 20210903130950

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20210903151041
=> Promote testgroup/testapp in dev to 20210903151041

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20210903151041
=> Promote testgroup/testapp in qa to 20210903151041

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20210903151041
=> Promote testgroup/testapp in prod to 20210903151041

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20210903151226
=> Promote testgroup/testapp in dev to 20210903151226

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20210903151226
=> Promote testgroup/testapp in prod to 20210903151226

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20210903131844
=> Promote testgroup/testapp in dev to 20210903131844

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20210903131844
=> Promote testgroup/testapp in qa to 20210903131844

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20210903131844
=> Promote testgroup/testapp in prod to 20210903131844

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20210903132309
=> Promote testgroup/testapp in qa to 20210903132309

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20210903132309
=> Promote testgroup/testapp in prod to 20210903132309

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20210903132812
=> Promote testgroup/testapp in dev to 20210903132812

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20210903132812
=> Promote testgroup/testapp in qa to 20210903132812

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20210903132812
=> Promote testgroup/testapp in prod to 20210903132812

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20210903142123
=> Promote testgroup/testapp in dev to 20210903142123

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20210903142123
=> Promote testgroup/testapp in qa to 20210903142123

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20210903142123
=> Promote testgroup/testapp in prod to 20210903142123

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20210903150246
=> Promote testgroup/testapp in dev to 20210903150246

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20210903150246
=> Promote testgroup/testapp in qa to 20210903150246

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20210903150246
=> Promote testgroup/testapp in prod to 20210903150246

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20210903170616
=> Promote testgroup/testapp in qa to 20210903170616

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20210903170616
=> Promote testgroup/testapp in prod to 20210903170616

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20210903171658
=> Promote testgroup/testapp in dev to 20210903171658

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20210903171658
=> Promote testgroup/testapp in qa to 20210903171658

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20210903171658
=> Promote testgroup/testapp in prod to 20210903171658

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20210903152228
=> Promote testgroup/testapp in dev to 20210903152228

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20210903152728
=> Promote testgroup/testapp in dev to 20210903152728

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20210903152728
=> Promote testgroup/testapp in qa to 20210903152728

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20210903152728
=> Promote testgroup/testapp in prod to 20210903152728

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20210906095244
=> Promote testgroup/testapp in dev to 20210906095244

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20210906095244
=> Promote testgroup/testapp in qa to 20210906095244

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20210906095244
=> Promote testgroup/testapp in prod to 20210906095244

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20210906075932
=> Promote testgroup/testapp in dev to 20210906075932

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20210906075932
=> Promote testgroup/testapp in qa to 20210906075932

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20210906075932
=> Promote testgroup/testapp in prod to 20210906075932

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20210906081441
=> Promote testgroup/testapp in dev to 20210906081441

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20210906081441
=> Promote testgroup/testapp in qa to 20210906081441

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20210906081441
=> Promote testgroup/testapp in prod to 20210906081441

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20210907164904
=> Promote testgroup/testapp in qa to 20210907164904

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20210907164904
=> Promote testgroup/testapp in prod to 20210907164904

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20210907165110
=> Promote testgroup/testapp in dev to 20210907165110

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20210907165110
=> Promote testgroup/testapp in qa to 20210907165110

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20210907165110
=> Promote testgroup/testapp in prod to 20210907165110

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20210907221600
=> Promote testgroup/testapp in dev to 20210907221600

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20210907222306
=> Promote testgroup/testapp in dev to 20210907222306

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20210907223400
=> Promote testgroup/testapp in dev to 20210907223400

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20210907223400
=> Promote testgroup/testapp in qa to 20210907223400

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20210907223400
=> Promote testgroup/testapp in prod to 20210907223400

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20210907230956
=> Promote testgroup/testapp in dev to 20210907230956

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20210907230956
=> Promote testgroup/testapp in qa to 20210907230956

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20210907230956
=> Promote testgroup/testapp in prod to 20210907230956

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20210907232910
=> Promote testgroup/testapp in dev to 20210907232910

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20210907232910
=> Promote testgroup/testapp in qa to 20210907232910

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20210907232910
=> Promote testgroup/testapp in prod to 20210907232910

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20210907235552
=> Promote testgroup/testapp in dev to 20210907235552

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20210907235552
=> Promote testgroup/testapp in qa to 20210907235552

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20210907235552
=> Promote testgroup/testapp in prod to 20210907235552

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20210908001026
=> Promote testgroup/testapp in dev to 20210908001026

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20210908001026
=> Promote testgroup/testapp in qa to 20210908001026

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20210908001026
=> Promote testgroup/testapp in prod to 20210908001026

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20210908002659
=> Promote testgroup/testapp in dev to 20210908002659

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20210908002659
=> Promote testgroup/testapp in qa to 20210908002659

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20210908002659
=> Promote testgroup/testapp in prod to 20210908002659

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20210907224558
=> Promote testgroup/testapp in dev to 20210907224558

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20210907224558
=> Promote testgroup/testapp in qa to 20210907224558

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20210907224558
=> Promote testgroup/testapp in prod to 20210907224558

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20210907225534
=> Promote testgroup/testapp in dev to 20210907225534

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20210907225534
=> Promote testgroup/testapp in qa to 20210907225534

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20210907225534
=> Promote testgroup/testapp in prod to 20210907225534

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20210907233330
=> Promote testgroup/testapp in dev to 20210907233330

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20210907233330
=> Promote testgroup/testapp in qa to 20210907233330

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20210907233330
=> Promote testgroup/testapp in prod to 20210907233330

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20210908064811
=> Promote testgroup/testapp in dev to 20210908064811

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20210908064811
=> Promote testgroup/testapp in prod to 20210908064811

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20210908091509
=> Promote testgroup/testapp in qa to 20210908091509

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20210908091509
=> Promote testgroup/testapp in prod to 20210908091509

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20210908113152
=> Promote testgroup/testapp in dev to 20210908113152

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20210908113152
=> Promote testgroup/testapp in prod to 20210908113152

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20210908093819
=> Promote testgroup/testapp in dev to 20210908093819

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20210908093819
=> Promote testgroup/testapp in qa to 20210908093819

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20210908093819
=> Promote testgroup/testapp in prod to 20210908093819

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20210917095301
=> Promote testgroup/testapp in dev to 20210917095301

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20210917095301
=> Promote testgroup/testapp in qa to 20210917095301

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20210917100246
=> Promote testgroup/testapp in dev to 20210917100246

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20210917100246
=> Promote testgroup/testapp in qa to 20210917100246

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20210917100246
=> Promote testgroup/testapp in prod to 20210917100246

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20210917124139
=> Promote testgroup/testapp in dev to 20210917124139

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20210917124139
=> Promote testgroup/testapp in qa to 20210917124139

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20210917124139
=> Promote testgroup/testapp in prod to 20210917124139

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20210917125933
=> Promote testgroup/testapp in dev to 20210917125933

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20210917125933
=> Promote testgroup/testapp in qa to 20210917125933

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20210917125933
=> Promote testgroup/testapp in prod to 20210917125933

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20210917150747
=> Promote testgroup/testapp in dev to 20210917150747

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20210917150747
=> Promote testgroup/testapp in qa to 20210917150747

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20210917150747
=> Promote testgroup/testapp in prod to 20210917150747

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20210917151311
=> Promote testgroup/testapp in dev to 20210917151311

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20210917151311
=> Promote testgroup/testapp in qa to 20210917151311

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20210917152526
=> Promote testgroup/testapp in dev to 20210917152526

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20210917152526
=> Promote testgroup/testapp in qa to 20210917152526

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20210917152526
=> Promote testgroup/testapp in prod to 20210917152526

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20210917153813
=> Promote testgroup/testapp in dev to 20210917153813

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20210917153813
=> Promote testgroup/testapp in qa to 20210917153813

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20210917153813
=> Promote testgroup/testapp in prod to 20210917153813

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20211014125407
=> Promote testgroup/testapp in dev to 20211014125407

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20211014125407
=> Promote testgroup/testapp in prod to 20211014125407

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20211020123216
=> Promote testgroup/testapp in prod to 20211020123216

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20211101132213
=> Promote testgroup/testapp in dev to 20211101132213

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20211101132213
=> Promote testgroup/testapp in qa to 20211101132213

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20211101132213
=> Promote testgroup/testapp in prod to 20211101132213

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20211101133245
=> Promote testgroup/testapp in dev to 20211101133245

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20211101133245
=> Promote testgroup/testapp in qa to 20211101133245

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20211101133245
=> Promote testgroup/testapp in prod to 20211101133245

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20211101133348
=> Promote testgroup/testapp in dev to 20211101133348

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20211101133348
=> Promote testgroup/testapp in qa to 20211101133348

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20211101133348
=> Promote testgroup/testapp in prod to 20211101133348

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20211103090820
=> Promote testgroup/testapp in dev to 20211103090820

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20211103090820
=> Promote testgroup/testapp in qa to 20211103090820

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20211103090820
=> Promote testgroup/testapp in prod to 20211103090820

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20211108135431
=> Promote testgroup/testapp in dev to 20211108135431

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20211108135431
=> Promote testgroup/testapp in qa to 20211108135431

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20211108135431
=> Promote testgroup/testapp in prod to 20211108135431

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20211118170903
=> Promote testgroup/testapp in dev to 20211118170903

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20211118172004
=> Promote testgroup/testapp in dev to 20211118172004

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20211118172957
=> Promote testgroup/testapp in dev to 20211118172957

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20211118172957
=> Promote testgroup/testapp in qa to 20211118172957

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20211118172957
=> Promote testgroup/testapp in prod to 20211118172957

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20211118165006
=> Promote testgroup/testapp in dev to 20211118165006

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20211118165006
=> Promote testgroup/testapp in prod to 20211118165006

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20211119093325
=> Promote testgroup/testapp in dev to 20211119093325

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20211119093325
=> Promote testgroup/testapp in qa to 20211119093325

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20211119093325
=> Promote testgroup/testapp in prod to 20211119093325

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20211123135622
=> Promote testgroup/testapp in dev to 20211123135622

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20211123135622
=> Promote testgroup/testapp in qa to 20211123135622

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20211123135622
=> Promote testgroup/testapp in prod to 20211123135622

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20211123140213
=> Promote testgroup/testapp in dev to 20211123140213

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20211123140213
=> Promote testgroup/testapp in qa to 20211123140213

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20211123140213
=> Promote testgroup/testapp in prod to 20211123140213

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20211123141131
=> Promote testgroup/testapp in dev to 20211123141131

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20211123141131
=> Promote testgroup/testapp in qa to 20211123141131

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20211123141131
=> Promote testgroup/testapp in prod to 20211123141131

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20211124154103
=> Promote testgroup/testapp in dev to 20211124154103

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20211124154228
=> Promote testgroup/testapp in dev to 20211124154228

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20211124154228
=> Promote testgroup/testapp in qa to 20211124154228

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20211124154228
=> Promote testgroup/testapp in prod to 20211124154228

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20211124155819
=> Promote testgroup/testapp in dev to 20211124155819

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20211124171611
=> Promote testgroup/testapp in dev to 20211124171611

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20211124171904
=> Promote testgroup/testapp in dev to 20211124171904

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20211124171904
=> Promote testgroup/testapp in prod to 20211124171904

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20211124162655
=> Promote testgroup/testapp in dev to 20211124162655

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20211124173050
=> Promote testgroup/testapp in dev to 20211124173050

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20211124173050
=> Promote testgroup/testapp in qa to 20211124173050

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20211124173050
=> Promote testgroup/testapp in prod to 20211124173050

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20211124173453
=> Promote testgroup/testapp in dev to 20211124173453

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20211124173453
=> Promote testgroup/testapp in qa to 20211124173453

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20211124173453
=> Promote testgroup/testapp in prod to 20211124173453

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20211124173713
=> Promote testgroup/testapp in dev to 20211124173713

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20211124173713
=> Promote testgroup/testapp in qa to 20211124173713

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20211124173713
=> Promote testgroup/testapp in prod to 20211124173713

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20211124174221
=> Promote testgroup/testapp in dev to 20211124174221

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20211124174503
=> Promote testgroup/testapp in dev to 20211124174503

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20211124174634
=> Promote testgroup/testapp in dev to 20211124174634

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20211124174806
=> Promote testgroup/testapp in dev to 20211124174806

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20211124174806
=> Promote testgroup/testapp in qa to 20211124174806

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20211124174806
=> Promote testgroup/testapp in prod to 20211124174806

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20211124165522
=> Promote testgroup/testapp in dev to 20211124165522

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20211124165522
=> Promote testgroup/testapp in qa to 20211124165522

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20211124165522
=> Promote testgroup/testapp in prod to 20211124165522

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20211124180732
=> Promote testgroup/testapp in dev to 20211124180732

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20211124180732
=> Promote testgroup/testapp in qa to 20211124180732

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20211124180732
=> Promote testgroup/testapp in prod to 20211124180732

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20211125193147
=> Promote testgroup/testapp in dev to 20211125193147

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20211125193147
=> Promote testgroup/testapp in qa to 20211125193147

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20211125193147
=> Promote testgroup/testapp in prod to 20211125193147

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20211125193335
=> Promote testgroup/testapp in dev to 20211125193335

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20211125193335
=> Promote testgroup/testapp in qa to 20211125193335

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20211125193335
=> Promote testgroup/testapp in prod to 20211125193335

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20211125223540
=> Promote testgroup/testapp in dev to 20211125223540

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20211125224421
=> Promote testgroup/testapp in dev to 20211125224421

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20211125224421
=> Promote testgroup/testapp in qa to 20211125224421

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20211125232532
=> Promote testgroup/testapp in dev to 20211125232532

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20211125232532
=> Promote testgroup/testapp in qa to 20211125232532

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20211125232532
=> Promote testgroup/testapp in prod to 20211125232532

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20211126000438
=> Promote testgroup/testapp in dev to 20211126000438

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20211126000438
=> Promote testgroup/testapp in qa to 20211126000438

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20211126000438
=> Promote testgroup/testapp in prod to 20211126000438

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20211126084751
=> Promote testgroup/testapp in dev to 20211126084751

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20211126084751
=> Promote testgroup/testapp in qa to 20211126084751

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20211126084751
=> Promote testgroup/testapp in prod to 20211126084751

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20211126142918
=> Promote testgroup/testapp in dev to 20211126142918

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20211126142918
=> Promote testgroup/testapp in qa to 20211126142918

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20211126142918
=> Promote testgroup/testapp in prod to 20211126142918

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20211126133928
=> Promote testgroup/testapp in dev to 20211126133928

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20211126133928
=> Promote testgroup/testapp in qa to 20211126133928

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20211126133928
=> Promote testgroup/testapp in prod to 20211126133928

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20211126140250
=> Promote testgroup/testapp in dev to 20211126140250

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20211126140250
=> Promote testgroup/testapp in qa to 20211126140250

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20211126140250
=> Promote testgroup/testapp in prod to 20211126140250

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20211126150315
=> Promote testgroup/testapp in dev to 20211126150315

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20211126150315
=> Promote testgroup/testapp in qa to 20211126150315

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20211126150315
=> Promote testgroup/testapp in prod to 20211126150315

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20211126154946
=> Promote testgroup/testapp in dev to 20211126154946

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20211126154946
=> Promote testgroup/testapp in qa to 20211126154946

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20211126154946
=> Promote testgroup/testapp in prod to 20211126154946

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20211126170736
=> Promote testgroup/testapp in dev to 20211126170736

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20211126173255
=> Promote testgroup/testapp in dev to 20211126173255

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20211126173352
=> Promote testgroup/testapp in dev to 20211126173352

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20211126173352
=> Promote testgroup/testapp in qa to 20211126173352

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20211126173750
=> Promote testgroup/testapp in dev to 20211126173750

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20211126173750
=> Promote testgroup/testapp in qa to 20211126173750

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20211126173750
=> Promote testgroup/testapp in prod to 20211126173750

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20211126173930
=> Promote testgroup/testapp in dev to 20211126173930

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20211126173930
=> Promote testgroup/testapp in qa to 20211126173930

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20211126173930
=> Promote testgroup/testapp in prod to 20211126173930

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20211129092912
=> Promote testgroup/testapp in dev to 20211129092912

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20211129093428
=> Promote testgroup/testapp in dev to 20211129093428

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20211129093428
=> Promote testgroup/testapp in qa to 20211129093428

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20211129093428
=> Promote testgroup/testapp in prod to 20211129093428

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20211129084119
=> Promote testgroup/testapp in dev to 20211129084119

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20211129084119
=> Promote testgroup/testapp in qa to 20211129084119

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20211129084119
=> Promote testgroup/testapp in prod to 20211129084119

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20211129101506
=> Promote testgroup/testapp in dev to 20211129101506

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20211129101506
=> Promote testgroup/testapp in qa to 20211129101506

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20211129101506
=> Promote testgroup/testapp in prod to 20211129101506

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20211129093906
=> Promote testgroup/testapp in dev to 20211129093906

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20211129093906
=> Promote testgroup/testapp in qa to 20211129093906

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20211129093906
=> Promote testgroup/testapp in prod to 20211129093906

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20211129094623
=> Promote testgroup/testapp in dev to 20211129094623

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20211129094623
=> Promote testgroup/testapp in qa to 20211129094623

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20211129094623
=> Promote testgroup/testapp in prod to 20211129094623

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20211129105402
=> Promote testgroup/testapp in dev to 20211129105402

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20211129105402
=> Promote testgroup/testapp in qa to 20211129105402

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20211129105402
=> Promote testgroup/testapp in prod to 20211129105402

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20211129101019
=> Promote testgroup/testapp in dev to 20211129101019

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20211129101019
=> Promote testgroup/testapp in qa to 20211129101019

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20211129101019
=> Promote testgroup/testapp in prod to 20211129101019

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20211129112221
=> Promote testgroup/testapp in dev to 20211129112221

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20211129112221
=> Promote testgroup/testapp in qa to 20211129112221

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20211129112221
=> Promote testgroup/testapp in prod to 20211129112221

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20211129113034
=> Promote testgroup/testapp in dev to 20211129113034

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20211129113034
=> Promote testgroup/testapp in qa to 20211129113034

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20211129113034
=> Promote testgroup/testapp in prod to 20211129113034

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20211129114154
=> Promote testgroup/testapp in dev to 20211129114154

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20211129114154
=> Promote testgroup/testapp in qa to 20211129114154

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20211129114154
=> Promote testgroup/testapp in prod to 20211129114154

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20211129123411
=> Promote testgroup/testapp in dev to 20211129123411

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20211129123411
=> Promote testgroup/testapp in prod to 20211129123411

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20211129233403
=> Promote testgroup/testapp in dev to 20211129233403

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20211129233403
=> Promote testgroup/testapp in qa to 20211129233403

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20211129233403
=> Promote testgroup/testapp in prod to 20211129233403

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20211129225344
=> Promote testgroup/testapp in dev to 20211129225344

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20211129231748
=> Promote testgroup/testapp in dev to 20211129231748

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20211129231748
=> Promote testgroup/testapp in qa to 20211129231748

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20211129231748
=> Promote testgroup/testapp in prod to 20211129231748

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20211201044225
=> Promote testgroup/testapp in dev to 20211201044225

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20211201044225
=> Promote testgroup/testapp in qa to 20211201044225

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20211201044225
=> Promote testgroup/testapp in prod to 20211201044225

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20211202081634
=> Promote testgroup/testapp in dev to 20211202081634

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20211202081634
=> Promote testgroup/testapp in qa to 20211202081634

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20211202081634
=> Promote testgroup/testapp in prod to 20211202081634

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20211202084720
=> Promote testgroup/testapp in dev to 20211202084720

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20211202084720
=> Promote testgroup/testapp in qa to 20211202084720

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20211202084720
=> Promote testgroup/testapp in prod to 20211202084720

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20211203045247
=> Promote testgroup/testapp in dev to 20211203045247

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20211203045247
=> Promote testgroup/testapp in qa to 20211203045247

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20211203045247
=> Promote testgroup/testapp in prod to 20211203045247

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20211213142249
=> Promote testgroup/testapp in dev to 20211213142249

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20211213142249
=> Promote testgroup/testapp in qa to 20211213142249

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20211213142249
=> Promote testgroup/testapp in prod to 20211213142249

testgroup/dev/testapp.yaml
ENV: dev
APP: testapp
TAG: 20211214043323
=> Promote testgroup/testapp in dev to 20211214043323

testgroup/qa/testapp.yaml
ENV: qa
APP: testapp
TAG: 20211214043323
=> Promote testgroup/testapp in qa to 20211214043323

testgroup/prod/testapp.yaml
ENV: prod
APP: testapp
TAG: 20211214043323
=> Promote testgroup/testapp in prod to 20211214043323
